version: "2"
services:
  app:
    build: . 
    restart: always
    environment:
      - RUN_MIGRATIONS=true
    volumes:
      - covers:/railsapp/public/cover
    ports:
      - "3005:3000"

volumes:
  covers:

