services:
  libretpv:
    image: sanraro/libretpv
    container_name: app 
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      RUN_MIGRATIONS: 'true'
      DB_HOST: db
      DB_USER: libretpv 
      DB_PASS: libretpv 
      DB_NAME: libretpv 
    volumes:
      - covers:/railsapp/public/cover
      - log:/railsapp/log

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: libretpv 
      MYSQL_USER: libretpv 
      MYSQL_PASSWORD: libretpv 
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  covers:
  log:
  db:
